configured_endpoints: 12
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/solomon-ai-yoanyombapro1234/workspace-financial-backend-sdk-aa6dca5ab10b6bebe2edebdeb4a93de502daf608204ce1bd7a5179b714578abc.yml
openapi_spec_hash: 1afbb0e63ac7b3deef561b61c5a3d6a7
config_hash: af10be0af89dc76c62ef05c460d0ccd7
