configured_endpoints: 12
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/solomon-ai-yoanyombapro1234%2Fworkspace-financial-backend-sdk-4be3d74cc41d8bb1ac27102a1de728cb9bf64ea397746bb19c2cc1de82123b28.yml
openapi_spec_hash: bf9f245a01672b1639352fb426d059da
config_hash: af10be0af89dc76c62ef05c460d0ccd7
